name: gestao_aluguel
description: "App para gerenciamento de pagamentos de aluguel."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Banco de dados local
  sqflite: ^2.3.3+1
  path: ^1.9.0
  
  # Para formatação de datas
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
